E-CommercePortal/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProceedToBuyRepository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace E_CommercePortal.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        HttpClient client;
        public CartController()
        {
            //proRepo = pRepo;
            client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:9000/CartSvc/");
        }
        // GET: CartController
        public async Task<ActionResult> Index()

        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<Cart> carts = await client.GetFromJsonAsync<List<Cart>>("");
            return View(carts);
        }

        // GET: CartController/Details/5
        [Route("GetCartByCustIdAndProId/{custId}/{proId}")]
        public async Task<ActionResult> Details(string custId,string proId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            Cart cart = await client.GetFromJsonAsync<Cart>("GetCartByCustomerIdAndProductId/" + custId + "/" + proId);
            return View(cart);
        }
        // GET: CartController/Details/5
        [Route("GetCartsByProId/{proId}")]
        public async Task<ActionResult> GetCartsByProductId( string proId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<Cart> carts = await client.GetFromJsonAsync<List<Cart>>("GetCartsByProductId/" + proId);
            return View(carts);
        }

        //[Route("GetVendorStock/{venId}/{proId}")]
        public async Task<VendorStock> GetVendorStock(string venId,string proId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            try
            {
                VendorStock venStock = await client.GetFromJsonAsync<VendorStock>("getVendorStockOfProduct/" + venId + "/" + proId);
                return venStock;
            }
            catch (Exception)
            {
                throw new Exception("Product not available");
               
            }
        }


        // GET: CartController/Create
        public ActionResult AddToCart()
        {

            return View();
        }
        

        // POST: CartController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddToCart(Cart cart)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            VendorStock venStock =  await GetVendorStock(cart.VendorId, cart.ProductId);
                if (venStock.StockInHand != 0)
                {
                    await client.PostAsJsonAsync<Cart>("",cart);
                    
                    return View("CartSuccess");

                }
                else
                {
                //filter required
                    
                    return View("CartError");
                    
                }
                              
                
                
           
        }

        /*// POST: CartController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddToCart(Cart cart)
        {
            try
            {
                VendorStock venStock = await client.GetFromJsonAsync<VendorStock>("VendorStock/getVendorStockOfProduct/V001/P001");
                if (venStock.StockInHand != 0)
                {
                    await client.PostAsJsonAsync<Cart>("", cart);
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    throw new Exception("not in stock");
                }



            }
            catch
            {
                return View();
            }
        }*/



        // GET: CartController/Delete/5
        [Route("Delete/{custId}/{proId}")]
        public async Task<ActionResult> Delete(string custId,string proId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            Cart cart = await client.GetFromJsonAsync<Cart>("GetCartByCustomerIdAndProductId/" + custId + "/" + proId);
            return View(cart);
            
        }

        // POST: CartController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Delete/{custId}/{proId}")]
        public async Task<ActionResult> Delete(string custId,string proId, IFormCollection collection)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
           
                await client.DeleteAsync("DeleteCart/" + custId + "/" + proId);
                return RedirectToAction(nameof(Index));
           
        }
    }
}

E-CommercePortal/Controllers/ProductRatingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProductRepository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace E_CommercePortal.Controllers
{
    [Authorize]
    public class ProductRatingController : Controller
    {
        HttpClient client;
        public ProductRatingController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:9000/ProductRatingSvc/");
        }

        public async Task<ActionResult> Index()
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            List<ProductRating> ratings = await client.GetFromJsonAsync<List<ProductRating>>("");
            return View(ratings);
        }

        // GET: ProductRatingController
        [Route("RatingsOfProduct/{proId}")]
        public async Task<ActionResult> RatingsOfProduct(string proId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<ProductRating> pRatings = await client.GetFromJsonAsync<List<ProductRating>>("RatingsOfProduct/"+proId);
            return View(pRatings);
        }

       

        // GET: ProductRatingController/Create
        public ActionResult AddProductRating()
        {
            return View();
        }

        // POST: ProductRatingController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<ActionResult> AddProductRating(ProductRating proRating)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            await client.PostAsJsonAsync<ProductRating>("", proRating);
            return RedirectToAction(nameof(Index));
           
        }
    }
}

E-CommercePortal/Controllers/WishlistController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProceedToBuyRepository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace E_CommercePortal.Controllers
{
    [Authorize]
    public class WishlistController : Controller
    {
        HttpClient client;
        public WishlistController()
        {
            client = new HttpClient();
            client.BaseAddress=new Uri("http://localhost:9000/WishlistSvc/");
        }
        // GET: WishlistController
        [Route("GetAllWishlist")]
        public async Task<ActionResult> Index()
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<WishList> wLists = await client.GetFromJsonAsync<List<WishList>>("");
            return View(wLists);
        }

        //GET:Wishlist/GetWishlistsByProductId
        [Route("GetWishlistsByProductId/{proId}")]
        public async Task<ActionResult> GetWishlistByProductId(string proId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<WishList> wLists = await client.GetFromJsonAsync<List<WishList>>("GetWishlistsByProductId/"+proId);
            return View(wLists);
        }
        //GET:Wishlist/GetWishlistsByCustomerId
        [Route("GetWishlistsByCustomerId/{custId}")]
        public async Task<ActionResult> GetWishlistByCustomerId(string custId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<WishList> wLists = await client.GetFromJsonAsync<List<WishList>>("GetWishListsByCustomerId/" + custId);
            return View(wLists);
        }

        // GET: WishlistController/Details/5
        [Route("WishlistDetails/{custId}/{proId}")]
        public async Task<ActionResult> WishlistDetails(string custId,string proId)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            WishList wList = await client.GetFromJsonAsync<WishList>("GetWishListByCustomerIdAndProductId/" + custId + "/" + proId);
            return View(wList);
        }

        // GET: WishlistController/Create
        public ActionResult AddToWishlist()
        {
            
            return View();
        }

        // POST: WishlistController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddToWishlist(WishList wList)
        {
            string userName = User.Identity.Name;
            string roleName = User.Claims.ToArray()[4].Value;
            string token = await client.GetStringAsync("http://localhost:9000/AuthSvc/?userName=" + userName + "&role=" + roleName + "&key=My name is James Bond");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
           
                await client.PostAsJsonAsync<WishList>("", wList);
                return RedirectToAction(nameof(Index));
            
        }

        
        
        
    }
}

E-CommercePortal/Views/Cart/AddToCart.cshtml
@model ProceedToBuyRepository.Models.Cart

@{
    ViewData["Title"] = "AddToCart";
}

<h1>AddToCart</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddToCart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CartId" class="control-label"></label>
                <input asp-for="CartId" class="form-control" />
                <span asp-validation-for="CartId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendorId" class="control-label"></label>
                <input asp-for="VendorId" class="form-control" />
                <span asp-validation-for="VendorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label"></label>
                <input asp-for="DeliveryDate" class="form-control" />
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

E-CommercePortal/Views/Cart/CartError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">Product cannot be added to cart, please add product to WishList!</h2>
<a class="nav-link text-dark" asp-area="" asp-controller="Wishlist" asp-action="AddToWishlist">Add To WishList!</a>

E-CommercePortal/Views/Cart/CartSuccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1 class="text-success">Success.</h1>
<h2 class="text-success">Product Successfully added to Cart!</h2>
<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Back to Home page!</a>
<a class="btn btn-primary" href="@Url.Action("AddProductRating", "ProductRating")">Give Rating to this Product!</a>

E-CommercePortal/Views/Cart/Delete.cshtml
@model ProceedToBuyRepository.Models.Cart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CartId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CartId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VendorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VendorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

E-CommercePortal/Views/Cart/Details.cshtml
@model ProceedToBuyRepository.Models.Cart

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CartId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CartId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VendorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VendorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

E-CommercePortal/Views/Cart/GetCartsByProductId.cshtml
@model IEnumerable<ProceedToBuyRepository.Models.Cart>

@{
    ViewData["Title"] = "GetCartsByProductId";
}

<h1>GetCartsByProductId</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CartId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VendorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zipcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CartId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VendorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

E-CommercePortal/Views/Cart/GetVendorStock.cshtml
@model ProceedToBuyRepository.Models.VendorStock

@{
    ViewData["Title"] = "GetVendorStock";
}

<h1>GetVendorStock</h1>

<div>
    <h4>VendorStock</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VendorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VendorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockInHand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockInHand)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

E-CommercePortal/Views/Cart/Index.cshtml
@model IEnumerable<ProceedToBuyRepository.Models.Cart>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="AddToCart">Add To Cart</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CartId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VendorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zipcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CartId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VendorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeliveryDate)
            </td>
            <td>
               
                @Html.ActionLink("Details", "Details", new { custId=item.CustomerId,proId=item.ProductId }) |
                @Html.ActionLink("Delete", "Delete", new { custId = item.CustomerId, proId = item.ProductId })
            </td>
        </tr>
}
    </tbody>
</table>